url: "https://www.exec.su" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "$ exec su -" # the name of your site, e.g. ACME Corp.
site.lang: "en-US"
include: [t/_uts2]
